name: gotham-city-crime-analysis

services:
  verify-file-structure:
    build:
      context: .
    container_name: verify-file-structure
    restart: 'no'  # no need to re-verify file structure
    env_file:
      - .env
    command: python stages/01-stage/files_check.py
    extra_hosts:  # send localhost traffic to the docker host, e.g. your laptop
        - "localhost:host-gateway"

  generate-embeddings:
    depends_on:
      verify-file-structure:
        condition: service_completed_successfully
    build:
      context: .
    container_name: generate-embeddings
    restart: 'no'  # no need to re-generate embeddings
    env_file:
      - .env
    command: python stages/02-stage/test_embedding_generation.py
    extra_hosts:  # send localhost traffic to the docker host, e.g. your laptop
        - "localhost:host-gateway"
    volumes:
      - torch-checkpoints:/root/.cache/torch/checkpoints/

  index-content:
    depends_on:
      generate-embeddings:
        condition: service_completed_successfully
    build:
      context: .
    container_name: index-content
    restart: 'no'  # no need to re-verify file structure
    env_file:
      - .env
    command: python stages/03-stage/index_all_modalities.py
    extra_hosts:  # send localhost traffic to the docker host, e.g. your laptop
        - "localhost:host-gateway"

  search-and-analyze:
    depends_on:
      index-content:
        condition: service_completed_successfully
    build:
      context: .
    container_name: search-and-analyze
    restart: 'no'  # no need to re-verify file structure
    env_file:
      - .env
    command: python stages/04-stage/rag_crime_analyze.py
    extra_hosts:  # send localhost traffic to the docker host, e.g. your laptop
        - "localhost:host-gateway"

volumes:
  # Avoid re-downloading a >4GB model checkpoint
  torch-checkpoints:
