version: '3.7'

services:
  api:
    build:
      context: ./app-api
      dockerfile: Dockerfile
    volumes:
      - './app-api:/usr/src/app'
    ports:
      - 8000:8000
    environment:
      - CLOUD_ID=demo-nlp-gai:dXMtZWFzdC0xLmF3cy5mb3VuZC5pbzo0NDMkYTQwZTdiY2ZiMzI5NDgxYzhmY2RjNDZhMTkwZGNiMjAkNWJlMTgyMGU2NzM2NDBjN2EyNGU2YzgzZWE5NTE3ZjU=
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=4fpcJvy5HXB10Lc0U1BP641b

  client:
    build:
      context: ./app-ui
      dockerfile: Dockerfile
    volumes:
      - './app-ui:/usr/src/app'
    ports:
      - 3000:3000
    environment:
      - NEXT_API_URL=http://host.docker.internal:8000
    depends_on:
      - api
