services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: >
      sh -c "
        /bin/ollama serve &
        sleep 5 &&
        /bin/ollama run qwen3:4b &&
        wait
      "
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local